### ISSUE TITLE
能不能别把cmake搞得那么新哦

### ISSUE THREAD

**Issue by yujack008** [LSPosed/LSPlant#100]
AS最新的cmake版本是3.22.1，而工程代码要求cmake版本是3.28.0+
![1722849463503](https://github.com/user-attachments/assets/81acaf97-30f6-44e4-a58a-298f1c7baab0)

导致编译不通过，报了如下错误：

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  
  
  CMake Error:
    The Ninja generator does not support C++20 modules using Ninja version
  
      1.8.2
  
    due to lack of required features.  Ninja 1.11 or higher is required.
  
  
  CMake Error in external/dex_builder/CMakeLists.txt:
    The target named "dex_builder_static" has C++ sources that may use modules,
    but modules are not supported by this generator:
  
      Ninja
  
    Modules are supported only by Ninja, Ninja Multi-Config, and Visual Studio
    generators for VS 17.4 and newer.  See the cmake-cxxmodules(7) manual for
    details.  Use the CMAKE_CXX_SCAN_FOR_MODULES variable to enable or disable
    scanning.

**Comment by vvb2060** [comment]
CI能过你不能过？

**Comment by yujincheng08** [comment]
sdk 带的 cmake 很久没更新了，而且让 ndk 的人去更新他们也说没空。自己装个 cmake 和 ninja 才是正道。

**Comment by thouger** [comment]
是的，痛苦，要不gradle是超新的，要不cmake是超新的，还有那个什么agp，每一次都超出androidstudio 所支持的范围..
