### ISSUE TITLE
SetEntryPoint代码请教

### ISSUE THREAD

**Issue by yujack008** [LSPosed/LSPlant#103]
看到如下代码有点困惑：    
void SetEntryPoint(void *entry_point) {
       //第一个entry_point
        *reinterpret_cast<void **>(reinterpret_cast<uintptr_t>(this) + entry_point_offset) =
            entry_point;
      //第二个entry_point
        if (interpreter_entry_point_offset) [[unlikely]] {
            *reinterpret_cast<void **>(reinterpret_cast<uintptr_t>(this) +
                                       interpreter_entry_point_offset) =
                reinterpret_cast<void *>(art_interpreter_to_compiled_code_bridgeSym);
        }
    }

我理解AtrMethod::Invoke入口有四个：
1.dex解析
2.JIT
3.OAT
4.Jni函数

请教一下，上面两个entry_point对应哪个入口呢？

**Comment by yujincheng08** [comment]
第一个
https://cs.android.com/android/platform/superproject/+/android-5.0.2_r1:art/runtime/mirror/art_method.h;drc=63bc11efaac0c041e849ab401f9fc368631a00f5;l=511

第二个
https://cs.android.com/android/platform/superproject/+/android-5.0.2_r1:art/runtime/mirror/art_method.h;drc=63bc11efaac0c041e849ab401f9fc368631a00f5;l=498
