### ISSUE TITLE
用LSPlant进行hook无法触发，用frida和LSPosed都可以触发，这可能是哪里没有处理好呢？

### ISSUE THREAD

**Issue by yujack008** [LSPosed/LSPlant#115]
单独使用LSPlant会出现hook无法触发的情况，已经使用Deoptimize对调用者进行去优化了。
不知道是哪里没有处理好，能否给点建议或者排查思路。
非常感谢！

**Comment by vvb2060** [comment]
日志

**Comment by yujack008** [comment]
> 看日志

报错信息：target method is not an executable

我用如下代码打印，是可以看到函数的：
  Method[] methods = utils_c.getDeclaredMethods();
  for (Method method: methods) {
      Log.e(TAG, "utils_c." + method.getName());
  }

函数内容如下：
    public static boolean a(){
       Object k = c.k;
       _monitor_enter(k);
       _monitor_exit(k);
       return c.i;
    }

**Comment by yujack008** [comment]
> 看日志

测试发现了个问题：
1.如果把hook框架放到系统的framework.jar里面，Hook无法触发。
2.如果把hook框架跟APP放到一起编译，HOOK可以触发。

一般是什么问题才导致上面的情况呢
