### ISSUE TITLE
Failed to init jit code cache

### ISSUE THREAD

**Issue by Krosxx** [LSPosed/LSPlant#117]
请教 一开始遇到 `Failed to init art method` 错误，使用 xz 库后，遇到下面错误，请问如何解决呢？ 

```
18464 18464 E LSPlant : Hook Fails: _ZN3art3jit12JitCodeCache19GarbageCollectCacheEPNS_6ThreadE
18464 18464 E LSPlant : Failed to init jit code cache
18464 18464 E LSPosed : Failed to init lsplant
```

**Comment by vvb2060** [comment]
很明显这不是库的问题

**Comment by iscle** [comment]
@vvb2060 sorry to revive this, but it is an issue with LSPlant. The method was removed from newer Android version (Android 15+).

**Comment by aviraxp** [comment]
@iscle https://github.com/LSPosed/LSPlant/commit/0d9faca38da7023fa39fc93383051a04458a3518
