### ISSUE TITLE
最新安卓15机型的libart.so缺少3个必要的符号

### ISSUE THREAD

**Issue by lbwengineer** [LSPosed/LSPlant#119]
先看完我写的东西啊，不要直接关闭

这三个符号都是确确实实被去掉了，我反编译libart.so后可以通过其它符号推断出目标地址，你看看这个问题要怎么更好地解决

![1](https://github.com/user-attachments/assets/e4b7b094-d558-4a2a-871b-0a54776fb974)
![1 1](https://github.com/user-attachments/assets/9f9ef962-e82e-433b-b5e0-ba87c3ba90fe)
![1 2](https://github.com/user-attachments/assets/68a93bff-62f0-40c9-beaa-9e9a3d7ed07d)
![1 3](https://github.com/user-attachments/assets/f48fa477-5ea2-450c-a8e9-1b387726c6cc)
![2 1](https://github.com/user-attachments/assets/875520e1-8272-483c-a174-37f89c048a59)

这是安卓15的libart.so下载链接：https://yaole.lanzouo.com/iQFDd2ejg2cb

**Comment by vvb2060** [comment]
既然你不愿意点过去看，我再发一遍

```
llvm-objcopy libart.so --dump-section .gnu_debugdata=dbg.xz
unxz dbg.xz
llvm-readelf -sW dbg | grep GetMethodShorty
llvm-readelf -sW dbg | grep art_quick_to_interpreter_bridge
llvm-readelf -sW dbg | grep art_quick_generic_jni_trampoline
```
> 先看完我写的东西啊，不要直接关闭

先动手照着做一遍，不要再开issue
