### ISSUE TITLE
HOOK不生效

### ISSUE THREAD

**Issue by lbwengineer** [LSPosed/LSPlant#120]

**Comment by lbwengineer** [comment]
目标方法为 android.content.AttributionSource.writeToParcel
运行平台 Redmi k60e Android14
release安装包hook之后此方法没有按预期执行回调，当安装包的xml加上android:debuggable="true"后hook就能生效了，想问问看这是怎么回事有没有办法解决

**Comment by lbwengineer** [comment]
使用Deoptimize后可以正常回调了，但是这种方法不好用，有没有办法全局禁止内联而且是对已经加载的类的所有方法都取消内联

**Comment by vvb2060** [comment]
有，原版XP。
