### ISSUE TITLE
请教一下关于优化

### ISSUE THREAD

**Issue by jackyyu118** [LSPosed/LSPlant#125]
我这边想在不调用Deoptimize和不使用inline hook的情况下去掉优化功能。

情况1：可以修改安卓源码
我目前的思路是根据inline hook点然后修改art源码。但是修改点有点多，感觉有点麻烦，有啥更好的方法吗？

情况2：不修改安卓源码
我看网上说是设置prop属性值，但是我这边试了不行，还是我没有设置对。有什么好的办法吗？

**Comment by aviraxp** [comment]
@jackyyu118

**Comment by jackyyu118** [comment]
> @jackyyu118

额，是不是@错人了

**Comment by lbwengineer** [comment]
android:debuggable="true"就可以去掉优化，简单方便

**Comment by jackyyu118** [comment]
> android:debuggable="true"就可以去掉优化，简单方便

这是改APP了，会被检测到

**Comment by lbwengineer** [comment]
> > android:debuggable="true"就可以去掉优化，简单方便
> 
> 这是改APP了，会被检测到

也可以参考Pine的disableProfileSaver做法
