### ISSUE TITLE
how to find the lsplantConfig.cmake

### ISSUE THREAD

**Issue by SharkFall** [LSPosed/LSPlant#16]
I'm Chiness too,so thank you very much for your reading first.
i used cmake to generate .cmake file,but i didnt find the lsplantConfig.cmake file.
please tell me how to find it,thanks very much.

**Comment by yujincheng08** [comment]
In your `build.gradle`:
```groovy
repositories {
    mavenCentral()
}

dependencies {
    implementation "org.lsposed.lsplant:lsplant:3.2"
}

android {
    buildFeatures {
        prefab true
    }
}
```

**Comment by SharkFall** [comment]
thanks very much,im gonna to have a try

**Comment by SharkFall** [comment]
i done as this,but also error.
my gradle version is 7.2,should i update it?
this is the error log:
CMake Error at CMakeLists.txt:16 (find_package):
  Could not find a package configuration file provided by "lsplant" with any
  of the following names:

    lsplantConfig.cmake
    lsplant-config.cmake

> In your `build.gradle`:
> 
> ```groovy
> repositories {
>     mavenCentral()
> }
> 
> dependencies {
>     implementation "org.lsposed.lsplant:lsplant:3.2"
> }
> 
> android {
>     buildFeatures {
>         prefab true
>     }
> }
> ```
