### ISSUE TITLE
反馈bug

### ISSUE THREAD

**Issue by SharkFall** [LSPosed/LSPlant#17]
android abi：x86
android version：7.1
target_method：a() void
replacement_method：b() void

Bug描述：
在hook方法，调用replacement.invok(owner,args)时抛出错误：
 Caused by: java.lang.IllegalArgumentException: Wrong number of arguments; expected 0, got 1
        at java.lang.reflect.Method.invoke(Native Method)
        at sharkfall.inc.test.Hooker.callback(Hooker.java:31)
        at LSPHooker_.a(LSP)

被hook方法和替换方法都没有参数，但是hook返回的args带了1个参数。这是没修改lsplant test hooker类时运行发生的。

我的解决方案：
（为了方便没有修改c层，只是简单处理了下）
public Object callback(Object[] args) throws InvocationTargetException, IllegalAccessException {
        if (args.length == 1) {
            return replacement.invoke(owner);
        } else {
            //hook后会多返回一个参数
            Object[] arg = new Object[args.length - 1];
            System.arraycopy(args, 0, arg, 1, args.length);
            return replacement.invoke(owner, arg);
        }
    }

如果这并不是一个bug，那么很抱歉打扰到了，请帮我删除掉这个issue，谢谢。

**Comment by yujincheng08** [comment]
那个是隐含的 this 对象

**Comment by SharkFall** [comment]
这样啊，抱歉了，那麻烦删掉这个issue
