### ISSUE TITLE
[Bug] deoptmizing in Android 13 not working

### ISSUE THREAD

**Issue by enskye** [LSPosed/LSPlant#29]
### What happened/什么情况

installing apps with different signatures is not working on Android 13, Pixel 4 XL stock ROM on October patch

### LSPosed version/LSPosed 版本

1.8.4 (6636)

### Android version/Android 版本

13

### Version of Core Patch/核心破解版本

4.0

### Logs/日志

![IMG_20221028_153111_201](https://user-images.githubusercontent.com/62252655/198587852-1ec69201-e50a-46a8-a325-b06cf45b40e5.jpg)

[services.jar](https://drive.google.com/file/d/12GriGzAk69RS4EzTIbvZRbWWzYRfkxAr/view)

[LSPosed logs]
(https://drive.google.com/file/d/12Ki8Tc_nxtBDUEOnSaLHc99hJdYdPXsr/view?usp=drivesdk)

**Comment by yujincheng08** [comment]
I still need some confirmation from you so i will send you some ver of lsposed for logging.

**Comment by yujincheng08** [comment]
[LSPosed-v1.8.4-6631-zygisk-debug.zip](https://github.com/LSPosed/LSPlant/files/9891144/LSPosed-v1.8.4-6631-zygisk-debug.zip)
Try if this build works

**Comment by enskye** [comment]
nope, it doesn't work. attaching logs
[LSPosed_2022-10-28T22_14_56.658425.zip](https://github.com/LSPosed/LSPlant/files/9891175/LSPosed_2022-10-28T22_14_56.658425.zip)

**Comment by yujincheng08** [comment]
[LSPosed-v1.8.4-6631-zygisk-debug.zip](https://github.com/LSPosed/LSPlant/files/9891344/LSPosed-v1.8.4-6631-zygisk-debug.zip)
How about this one?

**Comment by enskye** [comment]
> [LSPosed-v1.8.4-6631-zygisk-debug.zip](https://github.com/LSPosed/LSPlant/files/9891344/LSPosed-v1.8.4-6631-zygisk-debug.zip) How about this one?

this build works.
[LSPosed_2022-10-28T22_54_02.126452.zip](https://github.com/LSPosed/LSPlant/files/9891398/LSPosed_2022-10-28T22_54_02.126452.zip)
