### ISSUE TITLE
Not working on Android 13/Tiramisu (API 33)

### ISSUE THREAD

**Issue by vegedreamgagnoa** [LSPosed/LSPlant#4]
Tried LSPlant to hook android.app.Activity#getSystemService as a sample, the hook result returns true, but the callback has never been called. Why? trying to deoptimize not work. **It works on Android 6 ~ 12** though.

**Comment by yujincheng08** [comment]
Have you tried to invoke `android.app.Activity#getSystemService` by reflection?

**Comment by vegedreamgagnoa** [comment]
If I am not mistaken it requires the object/instance of `android.app.Activity`, isn't it? Which usually we don't have access to that (we only have access to the Activity we defined). It's quite hassle especially if we don't have access to the owner object.
Looking at the source, I am still not understand how this is different to/surpasses Pine or Whale - where with both frameworks I can easily hook that method.

**Comment by yujincheng08** [comment]
What I mean is just for testing...

**Comment by vegedreamgagnoa** [comment]
Oh, sorry - yeah, it works if I tried to invoke the backup using reflection.

**Comment by yujincheng08** [comment]
Not the backup.

What I mean is:
Hook, invoke the original method by reflection and see if the hook is invoked.

**Comment by vegedreamgagnoa** [comment]
Nope, not working - only works for Activity that I have defined, as I said.

**Comment by vegedreamgagnoa** [comment]
Yes! :)

**Comment by vegedreamgagnoa** [comment]
Cool, thanks for the hint. Can you also suggest how to find the caller of the method at runtime?

**Comment by vegedreamgagnoa** [comment]
This is working: https://github.com/LSPosed/LSPosed/blob/master/core/src/main/cpp/external/yahfa/src/HookMain.cpp

**Comment by yujincheng08** [comment]
are you hooking a normal app? LSPosed has disabled inline systemwisely so it may work.

**Comment by vegedreamgagnoa** [comment]
Yeah, I didn't build any Xposed/LSPosed module, just include this library and try on a normal app.
It's still not working as I had hoped, invoking the backup using reflection might be good but without the owner object, you can't really do anything...

**Comment by vegedreamgagnoa** [comment]
Why this closed? We still have a  discussion! ))

**Comment by yujincheng08** [comment]
> Not the backup.

**Comment by vegedreamgagnoa** [comment]
woops, sorry, I mean the original. edited :)

**Comment by yujincheng08** [comment]
> you should deoptimize the caller to make it work.

**Comment by vegedreamgagnoa** [comment]
@yujincheng08 I found this function getInstanceOfClasses on Android P and higher, might be able to use it to locate the instances/callers?

**Comment by yujincheng08** [comment]
Reflection is just for test. If a hook can be invoked by reflection but not by other callers, it's likely it's inlined.

And the solution is never to find the instances. The solution is to avoid the inline, like deoptimizing all possible callers or recompile the app with flags that disable the inline, etc.

**Comment by yujincheng08** [comment]
> Why this closed? We still have a discussion! ))

It's not a bug. Maybe we should move it to the discussion.
