### ISSUE TITLE
logging.hpp

### ISSUE THREAD

**Issue by w296488320** [LSPosed/LSPlant#51]
if add  add_definitions(-DLOG_DISABLED)

use of undeclared identifier 'PLOGE'
                PLOGE("mmap trampoline");

#define PLOGE(fmt, args...) LOGE(fmt " failed with %d: %s", ##args, errno, strerror(errno))
You may forget to set up the PLOGE (...) 0

**Comment by yujincheng08** [comment]
oh yes. will fix.
