### ISSUE TITLE
lsplant  may be a mark

### ISSUE THREAD

**Issue by w296488320** [LSPosed/LSPlant#52]
![image](https://github.com/LSPosed/LSPlant/assets/30716361/d626cd55-36c0-4217-9322-bfc48014a81b)
![image](https://github.com/LSPosed/LSPlant/assets/30716361/0fa45b16-9f70-45f6-adfd-7afe3e60e37f)
![image](https://github.com/LSPosed/LSPlant/assets/30716361/711a4473-9c4c-4df8-b28c-b5e947aa64e2)

My lsposed module, when choosing some software with "shell", found that it would crash. After analysis, the possible reason is that the Lsplant mark was found, because my module can not import & lt;lsplant.h&gt;, so there is no good way to solve this problem.
For some strings with marks, I think you can set it up using random strings.

**Comment by yujincheng08** [comment]
https://github.com/LSPosed/LSPlant/blob/a612522188d903a523fc6760cd4ee257c3224d8c/lsplant/src/main/jni/include/lsplant.hpp#L55
