### ISSUE TITLE
Use LSPlant in zygisk modules

### ISSUE THREAD

**Issue by nitanmarcel** [LSPosed/LSPlant#53]
Is it possible to integrame LSPlant in an zygisk module? I tried searching for way of doing it but I can't seem to find an optimal way of doing it. Is there a way to maybe use it in an ndk project and statically include lsposed in the zygisk library?

**Comment by BryanGIG** [comment]
Yes, you can use LsPlant in zygisk module

You just have to init LsPlant in your native and use java hook api such as [Maple](https://github.com/fengyuecanzhu/Maple) or anything else to be able hook from java

I've tried it, and it works

**Comment by yujincheng08** [comment]
LSPosed is also one example.

**Comment by nitanmarcel** [comment]
> Yes, you can use LsPlant in zygisk module
> 
> You just have to init LsPlant in your native and use java hook api such as [Maple](https://github.com/fengyuecanzhu/Maple) or anything else to be able hook from java
> 
> I've tried it, and it works

Won't that mean that I somehow have to load the dex with the java side of hooks into the process from zygisk.so? 

That's where I'm confused, Maple and some of the similar projects creates it's own zygisk.so file so I won't be able to load the hooks defined in java in the process. Or am I? Maybe I'm just setting up my projects in the wrong way.

**Comment by BryanGIG** [comment]
> 
> Won't that mean that I somehow have to load the dex with the java side of hooks into the process from zygisk.so? 
>

Yes, you need to load dex into your targeted process,

> 
> That's where I'm confused, Maple and some of the similar projects creates it's own zygisk.so file so I won't be able to load the hooks defined in java in the process. Or am I? Maybe I'm just setting up my projects in the wrong way.

You just need to take the java library and register the native function to your own zygisk.so, then you can call lsplant api from it

As, @LoveSpy said, LSPosed can be reference for this implementation

**Comment by nitanmarcel** [comment]
Ah, thanks to both.

Idk why I had the idea that LSPosed doesn't use LSPatch and they are different implementations for the same thing. Anyway looking a little more carefully at the lsposed repo I got a good example on how to use it in my own project.

Thanks, I appreciate it.

**Comment by socora097** [comment]
> Ах, спасибо вам обоим.
> 
> Не знаю, почему я решил, что LSPosed не использует LSPatch и что это разные реализации одного и того же. В любом случае, внимательно изучив репозиторий lsposed, я нашёл хороший пример того, как использовать его в своём проекте.
> 
> Спасибо, я ценю это.

скажи пожалуйста , ты нашел как правильно dex выгружать в zygisk?
