### ISSUE TITLE
Android8.0 hook方法会多出一个参数导致应用崩溃

### ISSUE THREAD

**Issue by zjhsdcc** [LSPosed/LSPlant#65]
Android8.0 hook方法会多出一个参数导致应用崩溃，hook的方法是Instrumentation类的callActivityOnResume方法
![1](https://github.com/LSPosed/LSPlant/assets/18672771/33cf8561-a887-4ec1-b430-314eedf51180)

**Comment by HarukaMomono** [comment]
看起来有点像第三方厂商修改的rom引起的...

**Comment by zjhsdcc** [comment]
Pixel 2手机，刷的是Google官方ROM

**Comment by zjhsdcc** [comment]
这应该是Hook框架对Android8.0系统的兼容性问题，我通过修改文件 art/runtime/art_method.hpp ，在Init方法中，将 if (sdk_int <= __ANDROID_API_O__）修改为 if (sdk_int < __ANDROID_API_O__）可以解决这个问题。
![1](https://github.com/LSPosed/LSPlant/assets/18672771/413d42ee-fadd-4de0-bafb-77045dc128b9)

**Comment by canyie** [comment]
可以试试用 https://github.com/canyie/pine
