### ISSUE TITLE
根据文档无法执行初始化

### ISSUE THREAD

**Issue by zmer007** [LSPosed/LSPlant#73]
初始化需要保证 art_symbol_resolver art_symbol_prefix_resolver 非空，测试示例中使用了

lsparself::Elf art("/libart.so");

进行初始化，但是实际使用过程中，无法获取 lsparself 源码或者库。

**Comment by yujincheng08** [comment]
那个只是 test。实际使用需要自己写个 elf 解析或者使用其他现有库。
