### ISSUE TITLE
如何hook一个无返回值带参数的函数，并修改函数参数呢？

### ISSUE THREAD

**Issue by anjiuzhe** [LSPosed/LSPlant#95]
你好，假设有一个函数为void test(LTest t)，需求是替换或修改函数的参数LTest t，在LSPlant没有找到相关的示例，请问用LSPlant可以实现这个需求吗？谢谢。

**Comment by yujincheng08** [comment]
可以

**Comment by anjiuzhe** [comment]
@yujincheng08 你好，我在LSPlant的项目中测试hook webview的setWebViewClient方法，想替换其中WebViewClient，但是两种实现方式都没有成功，请问需要怎么做呢？下面是关键代码：
<img width="861" alt="image" src="https://github.com/LSPosed/LSPlant/assets/30287547/b1d46eb2-e6e2-4cc2-bf85-6505b1abd1df">
<img width="658" alt="image" src="https://github.com/LSPosed/LSPlant/assets/30287547/bff56502-8ba1-462c-b779-614b56ea2270">

**Comment by yujincheng08** [comment]
替换之后得调用 backup，从你的代码完全看不到

**Comment by anjiuzhe** [comment]
@yujincheng08 感谢大佬指点，代码目前这样可以了。
<img width="900" alt="image" src="https://github.com/LSPosed/LSPlant/assets/30287547/06e1b788-0e22-4957-afab-527d23f5cad2">
但是调用backup的话，如果是对象方法，需要传入实际的对象，目前因为是测试，可以直接用变量保存，如果这个对象没法直接获取到，如何通过LSPlant来获取呢？

**Comment by yujincheng08** [comment]
args[0] 就是啊

**Comment by anjiuzhe** [comment]
谢谢大佬，这回懂了。
