### ISSUE TITLE
GarbageCollectCache method is removed in Android 15

### ISSUE THREAD

**Issue by JingMatrix** [LSPosed/LSPlant#97]
Since the [commit](https://cs.android.com/android/_/android/platform/art/+/e0e0f0740a1c1f4f28e1d1f59fe77625aea8d4a4), the method GarbageCollectCache is removed.
Hence, in `lsplant/src/main/jni/art/runtime/jit/jit_code_cache.hpp`, on should hook the symbol `_ZN3art3jit12JitCodeCache12DoCollectionEPNS_6ThreadE` instead of `_ZN3art3jit12JitCodeCache19GarbageCollectCacheEPNS_6ThreadE`.

Tested on Android 15, version: oriole_beta-ap31.240617.009.

**Comment by yujincheng08** [comment]
0d9faca38da7023fa39fc93383051a04458a3518
